name: Deploy to GitHub Pages

on: push

jobs: 
  deploy: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: '14'

    - name: Install Dependencies
      run: npm Install
    
    - name: Build
      run: npm run build
      env: 
        REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
        REACT_APP_SPOTIFY_REDIRECT_URI: ${{ secrets.REACT_APP_SPOTIFY_REDIRECT_URI }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build